name: Power Automate CI/CD Pipeline

on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Install Power Platform CLI (pac)
      - name: Install Power Platform CLI (pac)
        run: npm install -g pac-cli

      # Authenticate with Power Platform (Source Environment)
      - name: Authenticate with Power Platform (Source Environment)
        run: |
          pac auth create \
            --url https://make.powerautomate.com/environments/10615798-70d6-efb4-a25a-7c36b627d7d7 \
            --tenant 0804b8f6-e628-4fa1-9eae-181b1d6205a5 \
            --applicationId cf7ea4d3-743b-4b47-9575-a01d49169be6 \
            --clientSecret "FBI8Q~h03tyVq77yob_zpK4Mn0M-iGK5gKYW-cCl"

      # Export solution from source environment
      - name: Export solution from source environment
        run: |
          pac solution export \
            --environment 10615798-70d6-efb4-a25a-7c36b627d7d7 \
            --path "PAutomationGitTesting_1_0_0_3.zip" \
            --managed true

      # Validate exported solution
      - name: Validate exported solution
        run: |
          if [ ! -f "./PAutomationGitTesting_1_0_0_3.zip" ]; then
            echo "Error: PAutomationGitTesting_1_0_0_3.zip not found!"
            exit 1
          fi
          if [ ! -s "./PAutomationGitTesting_1_0_0_3.zip" ]; then
            echo "Error: PAutomationGitTesting_1_0_0_3.zip is empty!"
            exit 1
          fi

      # Configure Git user details
      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Commit and push solution
      - name: Commit and push solution
        run: |
          git add "PAutomationGitTesting_1_0_0_3.zip"
          git commit -m "Exported solution from source environment" || echo "Nothing to commit."
          git push || echo "Push failed. Check permissions or authentication."

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Install Power Platform CLI (pac)
      - name: Install Power Platform CLI (pac)
        run: npm install -g pac-cli

      # Authenticate with Power Platform (Target Environment)
      - name: Authenticate with Power Platform (Target Environment)
        run: |
          pac auth create \
            --url https://make.powerautomate.com/environments/8c75c40e-a5b3-e306-a0e5-9116c62957d7 \
            --tenant 0804b8f6-e628-4fa1-9eae-181b1d6205a5 \
            --applicationId cf7ea4d3-743b-4b47-9575-a01d49169be6 \
            --clientSecret "FBI8Q~h03tyVq77yob_zpK4Mn0M-iGK5gKYW-cCl"

      # Import solution into target environment
      - name: Import Solution into Target Environment
        run: |
          if [ -f "./PAutomationGitTesting_1_0_0_3.zip" ]; then
            echo "Starting solution import..."
            pac solution import \
              --path "PAutomationGitTesting_1_0_0_3.zip" \
              --environment 8c75c40e-a5b3-e306-a0e5-9116c62957d7 \
              --overwrite-unmanaged-customizations true \
              --log import.log || { echo "Solution import failed. Check logs for details."; exit 1; }
          else
            echo "Error: PAutomationGitTesting_1_0_0_3.zip not found!"
            exit 1
          fi

      # Verify import status
      - name: Verify Import Status
        run: |
          echo "Verifying solution import..."
          pac solution list --environment 8c75c40e-a5b3-e306-a0e5-9116c62957d7

      # Notify success
      - name: Notify success
        run: echo "Solution has been successfully deployed to the target environment." 
