name: Power Automate CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Install Power Platform CLI (pac)
      - name: Install Power Platform CLI (pac)
        run: npm install -g pac-cli

      # Authenticate with Power Platform (Source Environment)
      - name: Authenticate with Power Platform (Source Environment)
        run: |
          pac auth create \
            --environmentId 10615798-70d6-efb4-a25a-7c36b627d7d7 \
            --tenant 0804b8f6-e628-4fa1-9eae-181b1d6205a5 \
            --applicationId cf7ea4d3-743b-4b47-9575-a01d49169be6 \
            --clientSecret "FBI8Q~h03tyVq77yob_zpK4Mn0M-iGK5gKYW-cCl"

      # Export solution from source environment
      - name: Export solution from source environment
        run: |
          pac solution export \
            --environment 10615798-70d6-efb4-a25a-7c36b627d7d7 \
            --path automations.zip \
            --managed true

      # Configure Git user details before committing
      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Upload exported solution to repository
      - name: Upload solution to repository
        run: |
          git add automations.zip
          git commit -m "Exported solution from source environment"
          git push

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Install Power Platform CLI (pac)
      - name: Install Power Platform CLI (pac)
        run: npm install -g pac-cli

      # Authenticate with Power Platform (Target Environment)
      - name: Authenticate with Power Platform (Target Environment)
        run: |
          pac auth create \
            --environmentId 8c75c40e-a5b3-e306-a0e5-9116c62957d7 \
            --tenant 0804b8f6-e628-4fa1-9eae-181b1d6205a5 \
            --applicationId cf7ea4d3-743b-4b47-9575-a01d49169be6 \
            --clientSecret "FBI8Q~h03tyVq77yob_zpK4Mn0M-iGK5gKYW-cCl"

      # Import solution into target environment
      - name: Import solution into target environment
        run: |
          pac solution import \
            --path automations.zip \
            --environment 8c75c40e-a5b3-e306-a0e5-9116c62957d7 \
            --overwrite-unmanaged-customizations true

      # Notify success
      - name: Notify success
        run: echo "Solution has been successfully deployed to the target environment."
