name: Power Automate CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Ensure Node.js 14.x is used

      # Install Power Platform CLI (pac)
      - name: Install Power Platform CLI (pac)
        run: |
          npm install -g pac-cli  # Install pac-cli for interacting with Power Platform

      # Authenticate with Power Platform (Source Environment)
      - name: Authenticate with Power Platform (Source Environment)
        run: |
          pac auth create --url https://org7b407228.crm8.dynamics.com --tenant 0804b8f6-e628-4fa1-9eae-181b1d6205a5 --applicationId cf7ea4d3-743b-4b47-9575-a01d49169be6 --clientSecret FBI8Q~h03tyVq77yob_zpK4Mn0M-iGK5gKYW-cCl

      # Download automations.zip from the repository
      - name: Download automations.zip
        run: |
          curl -L -o ./automations.zip https://github.com/ArchanaP-Pp/NewRepositoryPP/raw/main/automations.zip

      # Check if the file has a "(1)" suffix and handle it
      - name: Handle file with "(1)" suffix
        run: |
          if [ -f "./automations.zip (1)" ]; then
            echo "Renaming file to automations.zip"
            mv "./automations.zip (1)" ./automations.zip
          else
            echo "File name is correct."
          fi

      # Configure Git user details
      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Check if the file exists and commit it
      - name: Commit and push solution
        run: |
          if [ -f "./automations.zip" ]; then
            git add ./automations.zip
            git commit -m "Exported solution"
            git push
          else
            echo "File not found: ./automations.zip"
            exit 1
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the build job

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Ensure Node.js 14.x is used

      # Install Power Platform CLI (pac)
      - name: Install Power Platform CLI (pac)
        run: |
          npm install -g pac-cli  # Install pac-cli for interacting with Power Platform

      # Authenticate with Power Platform (Target Environment)
      - name: Authenticate with Power Platform (Target Environment)
        run: |
          pac auth create --url https://orgd05c6c63.crm8.dynamics.com --tenant 0804b8f6-e628-4fa1-9eae-181b1d6205a5 --applicationId cf7ea4d3-743b-4b47-9575-a01d49169be6 --clientSecret FBI8Q~h03tyVq77yob_zpK4Mn0M-iGK5gKYW-cCl

      # Import Solution into Target Environment
      - name: Import Solution into Target Environment
        run: |
          pac solution import --path ./automations.zip --environment https://orgd05c6c63.crm8.dynamics.com --overwrite-unmanaged-customizations true

      # Notify success
      - name: Notify success
        run: |
          echo "Solution has been successfully deployed to the target environment."
